version: '3.4'

services:
  catalogdb:
    container_name: catalogdb
    restart: always
    ports:
      - 8518:27017
    volumes:
      - mongo_data:/data/db
  basketdb:
    container_name: basketdb
    restart: always  
    ports:
      - 6379:6379
    volumes:
      - redis_config:/opt/bitnami/redis/mounted-etc/redis.conf  
      - redis_data:/bitnami/redis/data     
  portainer:
    container_name: portainer
    ports:
      - 8080:7900
      - 9000:9000
    volumes:
      - portainer_data:/data
      - /var/run/docker.sock:/var/run/docker.sock  
  discountdb:
    container_name: discountdb
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin1234
      - POSTGRES_Db=DiscountDb
    ports:
      - "8519:5432"
    volumes:
      -  postgres_data:/var/lib/postgresql/data/  
  orderdb:
    container_name: orderdb
    restart: always
    ports:
      - 1999:1433
    environment:
      - SA_PASSWORD=1234@Abcd
      - ACCEPT_EULA="Y"    
    volumes:
      - sqlserver_data:/var/opt/mssql   
  pgadmin:
    container_name: pgadmin
    restart: always
    ports:
      - 9001:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=mostapha.mahdavi@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=admin1234            
    volumes:
      - pgadmin_data:/root/.pgadmin  
  rabbitmq:
    container_name: rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"           
  catalog.api:
    container_name: catalog.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings:ConnectionStrings=mongodb://catalogdb"
    depends_on:
      - catalogdb
    ports:
      - "7900:80"
  basket.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "CacheSettings:RedisConnection=basketdb:6379"
      - "GrpcSettings:DiscountUrl=discount.grpc"
      - "EventBusSettings:HostAddress=amqp://guest:guest@rabbitmq:5672"
    depends_on:
      - basketdb  
      - rabbitmq
    ports:
      - "7901:80"
  discount.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings:DiscountContext=Server=172.28.0.1;Port=8519;Database=DiscountDb;User Id=admin;Password=admin1234"
    depends_on:
      - discountdb
    ports:
      - "7902:80"
  discount.grpc:
    container_name: discount.grpc
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings:DiscountContext=Server=172.28.0.1;Port=8519;Database=DiscountDb;User Id=admin;Password=admin1234"
    depends_on:
      - discountdb
    ports:
      - "7903:80"
  order.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings:OrderConnection=Data Source=orderdb;Initial Catalog=OrderDb;Uid=sa;Pwd=1234@Abcd"
      - "EventBusSettings:HostAddress=amqp://guest:guest@rabbitmq:5672"
    depends_on:
      - orderdb  
      - rabbitmq 
    ports:
      - "7904:80"


  ocelotapigw:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - catalog.api
      - basket.api
      - discount.api
      - order.api   
    ports:
      - "5010:80"


  shopping.aggregator:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ApiSettings:CatalogUrl="http://catalog.api"
      - ApiSettings:BasketUrl="http://basket.api"
      - ApiSettings:OrderUrl="http://order.api"
    depends_on:
      - catalog.api
      - basket.api
      - discount.api
      - order.api   
    ports:
      - "7910:80"

